openapi: "3.0.0"
info:
  version: 1.0.0
  title: Paza Afrika OpenApi Specification
  description: This is paza Afrika OpenApi Specification
  termsOfService: http://pazaafrika/terms/
  contact:
    name: Paza Afrika API Team
    email: apiteam@pazaafrika
    url: http://pazaafrika.com
  license:
    name: MIT
    url: https://www.pazaafrika.com/licenses/LICENSE-2.0.html
servers:
  - url: http://api.pazaafrika.com
